language: python
python:
  - "nightly"
install:
  - pip install flake8
  - pip install pydocstyle
  - pip install pyroma
  - pip install -U setuptools
  - pip install vulture
script:
  - flake8 .
  - pydocstyle
  - pyroma .
  - vulture .